spring:
  security:
    basic:
      enable: false
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

ht:
  service:
    data:
      host: http://localhost:3000
      endpoint: /
  security:
    log-rounds: 10